# Generated by Django 5.1.5 on 2025-01-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_comment_date_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
    ]
