# Generated by Django 5.1.5 on 2025-01-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_content_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
    ]
