# Generated by Django 5.1.5 on 2025-01-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_comment_text_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='share_count',
        ),
    ]
