# Generated by Django 5.1.5 on 2025-01-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_userpost_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
