# Generated by Django 5.1.5 on 2025-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpost',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
