# Generated by Django 5.1.5 on 2025-01-29 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_userpost_like_count_userpost_share_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='share_count',
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('user', 'post')},
        ),
    ]
